image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - test
  - build

install_dependencies:
  stage: build
  script:
    - npm install
  tags:
    - nodejs

testing_apps:
  stage: test
  script: 
    - npm test
    - npm run coverage
    
