image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - docker info

stages:
  - build
  - test

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  tags:
    - docker

build_image:
  stage: build
  script:
    - docker build -t todo-apps-api .
    # - docker run --rm todo-apps-api 
  tags:
    - docker

testing_apps:
  stage: test
  script: 
    - npm test
    - npm run coverage


