image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - docker info

stages:
  - build
  - test

install_dependencies:
  stage: build
  script:
    - npm install
  # tags:
  #   - nodejs

build_image:
  script:
    - docker build -t todo-apps-api .
    # - docker run --rm todo-apps-api 

testing_apps:
  stage: test
  script: 
    - npm test
    - npm run coverage


