image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - test
  - build

install_dependencies:
  stage: build
  script:
    - npm install
    - echo $MONGO_URL
  artifacts:
    paths:
      - node_modules/
  services:
    - mongo:3.2
  variables:
    MONGO_URL: mongodb://mongo:27017/todos

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker info
    - docker build -t "${CI_REGISTRY_IMAGE}/todo-apps-api:${CI_COMMIT_SHORT_SHA}" .
    - docker images
  tags:
    - docker

compose_docker:
  stage: build 
  image: 
    name: docker/compose:latest
    entrypoint: ["/bin/sh", "-c"]
  variables:
    DOCKER_HOST: tcp://docker:2375
  services:
    - docker:dind
  script:
    - docker-compose build

testing_apps:
  stage: test
  script: 
    - npm test
    - npm run coverage


